USE ZHYFOUNDRY_CRM;

DELIMITER $$
CREATE TRIGGER `TRIG_UPDATE_TIME` BEFORE UPDATE ON `ENTERPRISE` FOR EACH ROW BEGIN
	IF OLD.COUNT_MAIL_SENT != NEW.COUNT_MAIL_SENT
	THEN
		SET NEW.LATEST_MAIL_SENT = CURRENT_TIMESTAMP;
	ELSE
		SET NEW.UPDATE_TIME = CURRENT_TIMESTAMP;
	END IF;
END
$$
DELIMITER ;